In [2]:
%load_ext autoreload
%autoreload 2

In [ ]:
# For import to colab
!git clone 

In [3]:
from bayesopt_playground.optimization_loops import optimization_loop, get_recommendation
from bayesopt_playground.acquistion_functions import mutli_fidelity_entropy_search
from bayesopt_playground.models import multi_fidelity_gp
from bayesopt_playground.benchmarks import rf_iris_benchmark, generate_benchmark_bounds, generate_objective_function

/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9/site-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(


In [13]:
# Setup benchmark
bounds = generate_benchmark_bounds(
    rf_iris_benchmark,
    fidelity_param="subsample",
    ignore_params=["max_depth", "min_samples_leaf", "min_samples_split"],
)
obj_function = generate_objective_function(
    rf_iris_benchmark,
    fidelity_param="subsample",
    ignore_params=["max_depth", "min_samples_leaf", "min_samples_split"],
)

In [11]:
model, x, obj = optimization_loop(
    multi_fidelity_gp,
    multi_fidelity_gp, 
    mutli_fidelity_entropy_search,
    objective_function=obj_function,
    bounds=bounds,
    initial_samples=20, 
    n_iter=5)

/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-07 to the diagonal
  warnings.warn(
/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  warnings.warn(
/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-05 to the diagonal
  warnings.warn(
/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-04 to the diagonal
  warnings.warn(
/Users/tlong/anaconda3/envs/bayesopt/lib/python3.9

In [14]:
get_recommendation(model=model, objective_function=obj_function, bounds=bounds)

recommended point:
tensor([[0.210, 1.000]], dtype=torch.float64)

objective value:
tensor([0.], dtype=torch.float64)


tensor([[0.210, 1.000]], dtype=torch.float64)

In [15]:
import torch
obj_function(torch.tensor([[0.210, 1.000]]), full_result=True)

[{'function_value': 0.0,
  'cost': 0.22768807411193848,
  'info': {'train_loss': 1.0,
   'val_loss': 0.0,
   'test_loss': 0.06666666666666665,
   'model_cost': 0.21411395072937012,
   'train_scores': {'acc': 0.0, 'bal_acc': 0.0, 'f1': 0.0, 'precision': 0.0},
   'train_costs': {'acc': 0.0, 'bal_acc': 0.0, 'f1': 0.0, 'precision': 0.0},
   'val_scores': {'acc': 1.0, 'bal_acc': 1.0, 'f1': 1.0, 'precision': 1.0},
   'val_costs': {'acc': 0.01357412338256836,
    'bal_acc': 0.013333797454833984,
    'f1': 0.013527154922485352,
    'precision': 0.013356924057006836},
   'test_scores': {'acc': 0.9333333333333333,
    'bal_acc': 0.9333333333333332,
    'f1': 0.9326599326599326,
    'precision': 0.9444444444444445},
   'test_costs': {'acc': 0.012419939041137695,
    'bal_acc': 0.013321161270141602,
    'f1': 0.01313018798828125,
    'precision': 0.013972997665405273},
   'fidelity': {'n_estimators': 512, 'subsample': 1.0},
   'config': {'max_depth': 10,
    'max_features': 0.20999999344348907,
  